--                SET DATEFORMAT DMY; 
SELECT TOP 3
  row_number() over(ORDER BY AGE_IN_CODIGO) AS AGE_IN_REALIZADASCODIGO,
  (M.MED_ST_NOME+'\n'+ 
  LTRIM(CONVERT(VARCHAR, AGE_DT_DATA, 103))+' '+
  CONVERT(VARCHAR(2), DATEPART(hh,AGE_DT_HORAINI))+':'+
  CONVERT(VARCHAR(2),DATEPART(n, AGE_DT_HORAINI))) AS AGE_ST_CONSREALIZADAS
 FROM CLI_AGENDA A, CLI_MEDICO M
WHERE A.MED_IN_CODIGO = M.MED_IN_CODIGO
  AND PAC_IN_CODIGO = 1
  AND AGE_DT_DATA >= '20/11/2009'
  AND AGE_ST_SITUACAO NOT IN ('LV','CC','CF')
ORDER BY AGE_DT_DATA DESC, AGE_DT_HORAINI DESC
