
SET DATEFORMAT DMY;

-- Datas Disponiveis
SELECT 
  row_number() over(order by AGE_DT_DATA) AS DDC_IN_CODIGO, 
  CONVERT(VARCHAR(2), DATEPART(dd, DIAS.AGE_DT_DATA)) AS DDC_ST_DIAS
FROM 
( select DISTINCT AGE_DT_DATA FROM CLI_AGENDA 
   WHERE MED_IN_CODIGO = 1
     AND AGE_DT_DATA BETWEEN '01/11/2009' AND '30/11/2009'
     AND AGE_ST_SITUACAO = 'LV'
) AS DIAS

--GROUP BY AGE_DT_DATA

 OVER (ORDER BY a.au_lname, a.au_fname) as rank


-- Horarios Disponiveis
SET DATEFORMAT DMY;
SELECT 
  AGE_IN_CODIGO,
  CONVERT(VARCHAR(2), DATEPART(hh,AGE_DT_HORAINI))+':'+ CONVERT(VARCHAR(2),DATEPART(n, AGE_DT_HORAINI)) AS HDC_ST_HORARIOS
  --,AGE_DT_HORAINI, AGE_DT_HORAFIM
FROM CLI_AGENDA
WHERE MED_IN_CODIGO = 1
  AND AGE_DT_DATA = '26/11/2009'
  AND AGE_ST_SITUACAO = 'LV'
ORDER BY AGE_DT_HORAINI


