--                SET DATEFORMAT DMY; 
SELECT T
  AGE_IN_CODIGO,
  (M.MED_ST_NOME+'\n'+ 
  LTRIM(CONVERT(VARCHAR, AGE_DT_DATA, 103))+' '+
  CONVERT(VARCHAR(2), DATEPART(hh,AGE_DT_HORAINI))+':'+
  CONVERT(VARCHAR(2),DATEPART(n, AGE_DT_HORAINI))
  + CASE WHEN AGE_ST_SITUACAO = 'CF' THEN '\nConfirmada' ELSE '' END 
  ) AS AGE_ST_CONSPENDENTES
 FROM CLI_AGENDA A, CLI_MEDICO M
WHERE A.MED_IN_CODIGO = M.MED_IN_CODIGO
  AND PAC_IN_CODIGO = 1
  AND (AGE_DT_DATA > '26/11/2009'
       OR (AGE_DT_DATA = '26/11/2009' AND  AGE_DT_HORAINI > dateadd(day, -datediff(day, 0, getdate()), getdate()) ))
  AND AGE_ST_SITUACAO NOT IN ('LV','CC')
ORDER BY AGE_DT_DATA DESC, AGE_DT_HORAINI DESC

select dateadd(day, -datediff(day, 0, getdate()), getdate())
